### ISSUE TITLE
NoClassDefFoundError 

### ISSUE THREAD

**Issue by mohitissar** [Manabu-GT/EtsyBlur#33]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
        at com.ms_square.etsyblur.RenderScriptBlur.isAvailable(RenderScriptBlur.java:51)
        at com.ms_square.etsyblur.Blur.<init>(Blur.java:21)
        at com.ms_square.etsyblur.BlurDialogFragment.onAttach(BlurDialogFragment.java:45)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1404)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:

**Comment by vbv1** [comment]
I'm also facing the same issue except I am on android x not support library android.

**Comment by xiaowang119** [comment]
Have you solved this problem~?

**Comment by TheGabCode** [comment]
You can try adding in your proguard-rules.pro

-keep class androidx.renderscript.** { *; }

allthough this is on androidx

**Comment by TheGabCode** [comment]
> Have you solved this problem~?

You can try adding in your proguard-rules.pro

-keep class androidx.renderscript.** { *; }

allthough this is on androidx
